# Generated by Django 5.0 on 2023-12-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalheTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoAluno', models.CharField(max_length=20)),
                ('codigoProfessor', models.CharField(max_length=20)),
                ('codigoTurma', models.CharField(max_length=20)),
            ],
        ),
    ]
