# Generated by Django 5.0 on 2023-12-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='registro',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='sexo',
            field=models.CharField(max_length=10),
        ),
    ]
